apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-frontend-angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ibm-ng-app
  template:
    metadata:
      labels:
        app: ibm-ng-app
    spec:
      containers:
        - name: ibm-ng-app
          image: your-docker-hub-repo/ibm-ng-app
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

