apiVersion: v1
kind: Service
metadata:
  name: ibm-ng-app-service
spec:
  selector:
    app: ibm-ng-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
